# Makefile for CS 455 extra credit assgt Fall 2017
#
#     gmake getfiles
#        Copies or links assignment files to current directory
#
#     gmake ectest
#        Makes ectest executable
#
#     gmake submit
#        Submits the assignment.
#

# need to use gmake

HOME = /auto/home-scf-06/csci455/
ASSGTS = $(HOME)/assgts
ASSGTDIR = $(HOME)/assgts/ec


test: test.o
	g++ -ggdb -Wall -Wno-sign-compare -o test test.o

